# deploy:
#   provider: pages
#   skip_cleanup: true
#   github_token: 014b1b1bcfd66e7c9b2acccab39d2390d0f2a14c  # Set in the settings page of your repository, as a secure variable
#   keep_history: true
#      on:
#        branch: master

language: ruby
rvm:
 - 2.2
 - jruby
